language: python
python:
- "2.7"

install:
- pip install coveralls
- pip install coverage
- pip install cothread==2.14


script: coverage run dls_feedback_manager/pytest/basic_unittest.py

after_success:
- coveralls
