language: python
python:
- "2.7"

before install:
- curl http://repo.varnish-cache.org/debian/GPG-key.txt | sudo apt-key add
- echo "deb http://epics.nsls2.bnl.gov/debian/ wheezy main contrib" | sudo tee -a /etc/apt/cources.list
- echo "deb-src http://epics.nsls2.bnl.gov/debian/ wheezy main contrib"
- sudo apt-get update -qq
- sudo apt-get install epics-dev

install:
- pip install coveralls
- pip install coverage
- pip install cothread==2.14
- git clone https://github.com/Araneidae/epicsdbbuilder.git epicsdbbuilder
- cd epicsdbbuilder && git checkout 4d46b0246856e3369ebdfde10c56221b2987ac36 && cd ..
- python epicsdbbuilder/setup.py install
- wget http://controls.diamond.ac.uk/downloads/python/pythonSoftIoc/2-11/pythonSoftIoc-2.11.tgz -O /tmp/pythonSoftIoc-2.11.tar.gz
- tar -xvf /tmp/pythonSoftIoc-2.11.tar.gz
- cd pythonSoftIoc-2.11 && make
- export PATH=$PATH:PWD/pythonSoftIoc-2.11/bin/

script: coverage run dls_feedback_manager/refact/manager_tests.py

after_success:
- coveralls
