language: python
python:
- "2.7"

install:
- pip install coveralls
- pip install coverage
- pip install cothread==2.14
- git clone https://github.com/Araneidae/epicsdbbuilder.git epicsdbbuilder
- python epicsdbbuilder/setup.py install

script: coverage run dls_feedback_manager/refact/manager_tests.py

after_success:
- coveralls
